<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ubuntu" name="seleniumTests.RemoteSetupAbraxas" tests="4" failures="0" timestamp="10 Jul 2013 14:11:28 GMT" time="47.090" errors="2">
  <testcase name="testAbraxas1" time="15.180" classname="seleniumTests.RemoteSetupAbraxas"/>
  <testcase name="testAbraxas4" time="15.683" classname="seleniumTests.RemoteSetupAbraxas">
    <error type="java.lang.AssertionError" message="expected [G端nstig kaufen &amp; verkaufen bei eBay.ch - dem Schweizer Online-Marktplatz] but found [Home :: abraxas.ch]">
      <![CDATA[java.lang.AssertionError: expected [G端nstig kaufen & verkaufen bei eBay.ch - dem Schweizer Online-Marktplatz] but found [Home :: abraxas.ch]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at seleniumTests.RemoteSetupAbraxas.testAbraxas4(RemoteSetupAbraxas.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
]]>
    </error>
  </testcase> <!-- testAbraxas4 -->
  <testcase name="testAbraxas3" time="7.795" classname="seleniumTests.RemoteSetupAbraxas">
    <error type="java.lang.AssertionError" message="expected [G端nstig kaufen &amp; verkaufen bei eBay.ch - dem Schweizer Online-Marktplatz] but found [Home :: abraxas.ch]">
      <![CDATA[java.lang.AssertionError: expected [G端nstig kaufen & verkaufen bei eBay.ch - dem Schweizer Online-Marktplatz] but found [Home :: abraxas.ch]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at seleniumTests.RemoteSetupAbraxas.testAbraxas3(RemoteSetupAbraxas.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
]]>
    </error>
  </testcase> <!-- testAbraxas3 -->
  <testcase name="testAbraxas2" time="8.432" classname="seleniumTests.RemoteSetupAbraxas"/>
</testsuite> <!-- seleniumTests.RemoteSetupAbraxas -->
